services:
  dev:
    image: node:22-bookworm-slim
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
    tty: true